# http://www.seleniumhq.org/download/

btcc:
  browser: chrome
  user: {email: protestaccount002, password: btcchinA1, trans_password: btcchina1}
  test_case:
#    - login

spot_usd:
  browser: firefox
  user: {email: protestaccount002, password: btcchinA1, trans_password: btcchina1}
  test_case:
#    - logout_user_access_landing_page

btcchina:
  browser: chrome
  user: {email: protestaccount002, password: btcchinA1, trans_password: btcchina1}
  test_case:
    - deposit
#    - homepage
#    - trade
#    - withdraw